```{r, child = "_setup.Rmd", include = FALSE}
```

# Buttons

Use `background_*()` to modify shiny's action buttons.

```{r}
actionButton("ab1", "Take action") %>%
  background_color("info")
```

With a couple other functions we can take our improvement a step further.

```{r}
actionButton("ab1", "Take action") %>%
  background_color("info") %>%
  border_color("info") %>%
  shadow("small")
```

Shiny's download buttons include `...`, so we can use the `.style` pronoun!

```{r}
downloadButton(
  .style %>%
    background_color("secondary") %>%
    border_color("secondary"),
  outputId = "db1",
  label = "Download",
  class = NULL
)
```

# Panels

```{r}
sidebarLayout(
  sidebarPanel(
    .style %>%
      background_color("primary"),
    "Sidebar panel"
  ),
  mainPanel(
    .style %>%
      background_color("secondary"),
    "Main panel"
  )
)
```

# Colors

```{r colors, echo=FALSE}
div(
  .style %>%
    flex_display() %>%
    flex_justify("between") %>%
    flex_wrap(),
  lapply(names(background_color_values), function(color) {
    div(
      .style %>%
        margin(3),
      div(
        .style %>%
          text_align("center"),
        color
      ),
      div(
        .style %>%
          padding(5) %>%
          background_color(color)
      )
    )
  })
)
```
